# Generated by Django 2.0 on 2017-12-20 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=255)),
                ('state', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254)),
                ('to_date', models.DateField()),
                ('start_station', models.CharField(max_length=16)),
                ('end_station', models.CharField(max_length=16)),
                ('memo', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
